### ISSUE TITLE
Amcrest AD410: Failed to read data

### ISSUE THREAD

**Issue by calisro** [rroller/dahua#148]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I am seeing errors appear in my home assistant log related to teh following:

Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:355
Integration: Dahua (documentation, issues)
First occurred: 4:39:16 PM (1 occurrences)
Last logged: 4:39:16 PM
Failed to read data: b' \x00\x00\x00DHIP\xdc^,f\x08\x00\x00\x00s\x04\x00\x00\x00\x00\x00\x00s\x04\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4093],[0,8191],[8191,8191],[8191,4093],[8191,0]],"EventID":10437,"EventSeq":222,"FrameSequence":3113933,"GroupID":222,"LocaleTime":"2022-01-25 16:39:16","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingBox":', error: substring not found, Line: 348

## Debug log

```text

I do not have debug logging enabled but I can enable it and wait for it to reoccur if that would help.

\x00\x00\x00DHIP\xdc^,f\x08\x00\x00\x00s\x04\x00\x00\x00\x00\x00\x00s\x04\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4093],[0,8191],[8191,8191],[8191,4093],[8191,0]],"EventID":10437,"EventSeq":222,"FrameSequence":3113933,"GroupID":222,"LocaleTime":"2022-01-25 16:39:16","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingBox":', error: substring not found, Line: 348


```

**Comment by gitrichhub** [comment]
I am experiencing the same error(?).  Started after lasted upgrade of Home Assistant.  Occurs once per hour.  Thanks.

2022-01-24 18:43:26 ERROR (Thread-4) [custom_components.dahua] Failed to read data: b' \x00\x00\x00DHIPl]\xbdi\x08\x00\x00\x00\xe3\x04\x00\x00\x00\x00\x00\x00\xe3\x04\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[2338.351948699059,3869.337464522073],[66.66072136059142,3994.116611940465],[73.66132867824264,8189.818548146599],[8191,8191],[8191,4000],[7438.281406045658,3705.564706311552]],"EventID":10001,"EventSeq":0,"FrameSequence":265275,"GroupID":0,"LocaleTime":"2022-01-24 18:43:26","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingBox":[6696,3800,7176,4824],"CarrierBag":0,"Center":[6936,4312],"Confidence":0,"DownClothes":0,"Express":0,"FaceFlag":0,"FaceRect":[0,0,0,0],"FrameSequence":265275,"Gender":0,"Glass":0,"HairStyle":0,"HasHat":0,"Helmet":0,"HumanRect":[0,0,0,0],"LowerBodyColor":[0,0,0,0],"MainColor":[0,0,0,0],"MessengerBag":0,"ObjectID":20,"ObjectType":"Human","Phone":0,"RelativeID":0,"SerialUUID":"","ShoulderBag":0,"So', error: substring not found, Line: 348

**Comment by calisro** [comment]
I'm actually also seeing others whichI don't know if I should include in this issue or not but i'll add them here and if you want a new issue, I can move them.

This seems like a timeout.  I would think this just retries?
```
Failed to sync device state
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('10.100.1.143', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/dahua/__init__.py", line 285, in _async_update_data
    light_v2 = await self.client.async_get_lighting_v2()
  File "/config/custom_components/dahua/client.py", line 147, in async_get_lighting_v2
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 671, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 656, in get
    response = await auth.request("GET", url)
  File "/config/custom_components/dahua/digest.py", line 46, in request
    response = await self.session.request(method, url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.100.1.143:80 ssl:default [Connect call failed ('10.100.1.143', 80)]
```

After the above timeout, I see this which is most likely related but again I hope this retries.  
```
Logger: custom_components.dahua
Source: helpers/update_coordinator.py:219
Integration: Dahua (documentation, issues)
First occurred: 3:27:38 PM (1 occurrences)
Last logged: 3:27:38 PM

Error fetching dahua data:
```

Then I received the 'failed to read data' above.  

I setup a ping monitor in HA to understand if the device is having connection issues but in the past 24 hours, there were zero issues.  Signal is strong.  After some time, I find my bell and motion is no longer alerting HA and I have a job to restart the integration to get it fixed up again.

**Comment by calisro** [comment]
Another comment.  When the errors appear above, the integration motion detection and doorbell presses are non-functional.  I need to restart the integration to get it working again.

action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 37a185xxxxxxxxxxxxxxx049d9xxxxxed1
    target:
      entity_id: binary_sensor.front_doorbell_button_pressed

**Comment by calisro** [comment]
For others experiencing this, this is now what I've added to an automation to restart it.  


```
alias: Dahua Reload
description: ''
trigger:
  - platform: event
    event_type: system_log_event
condition:
  - condition: template
    value_template: '{{ "Error fetching dahua data" in trigger.event.data.message[0] }}'
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 37axxxxxxxxxxxxxxxxxxxxxxx9cffed1
    target:
      entity_id: binary_sensor.front_doorbell_button_pressed
mode: single
```

**Comment by rroller** [comment]
Are you on the latest version of the integration?

**Comment by rroller** [comment]
Sorry, I see that you are. 0.9.34

I'm going to see if I can reproduce this. Thanks for the report.

**Comment by rroller** [comment]
I was able to reproduce this and found the bug with the parsing of the AD410 events.

It's fixed in `0.9.35` 

https://github.com/rroller/dahua/releases/tag/0.9.35

**Comment by rroller** [comment]
That didn't seem to fully fix this issue. I'm still digging in.

**Comment by calisro** [comment]
I'll install the latest, stop by auto-restarting automation and see if I can capture something.

**Comment by calisro** [comment]
This is still happening to me.  At some point motion detection stops, the ringing of the bell stops alerting and  functioning and I see these errors in the logs.

```
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"RtspSessionState","Data":{"Device":"10.100.1.183","LocaleTime":"2022-02-25 10:12:45","Port":44394,"SessionId":"1741237864''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Start","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4093],[0,8191],[8191,8191],[8191,4093],[8191,0]],"EventID":15369,"EventSeq":5154,"FrameSequence":21293825,"GroupID":5154,"LocaleTime":"2022-02-25 10:13:51","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingB''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","C''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Start","''
```

```
Failed to read data: b' \x00\x00\x00DHIP\xee<5m\x08\x00\x00\x00\xe2\x00\x00\x00\x00\x00\x00\x00\xe2\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"BackKeyLight","Data":{"LocaleTime":"2022-02-25 09:44:40","State":4,"UTC":1645800280.0},"Index":-1}]},"session":1832205550', error: Expecting ',' delimiter: line 1 column 204 (char 203), Line: 356
Failed to read data: b' \x00\x00\x00DHIP\xee<5m\x08\x00\x00\x00\xe2\x00\x00\x00\x00\x00\x00\x00\xe2\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"BackKeyLight","Data":{"LocaleTime":"2022-02-25 09:44:55","State":4,"UTC":1645800295.0},"Index":-1}]},"session":1832205550', error: Expecting ',' delimiter: line 1 column 204 (char 203), Line: 356
Failed to read data: b' \x00\x00\x00DHIP\xee<5m\x08\x00\x00\x00\xe8\x00\x00\x00\x00\x00\x00\x00\xe8\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"IntelliFrame","Data":{"Action":"Start","LocaleTime":"2022-02-25 09:45:23","UTC":1645800323.0},"Index":0}]},"session":1832', error: Expecting ',' delimiter: line 1 column 210 (char 209), Line: 356
Failed to read data: b' \x00\x00\x00DHIP\xee<5m\x08\x00\x00\x00\xe8\x00\x00\x00\x00\x00\x00\x00\xe8\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"IntelliFrame","Data":{"Action":"Start","LocaleTime":"2022-02-25 10:13:51","UTC":1645802031.0},"Index":0}]},"session":1832', error: Expecting ',' delimiter: line 1 column 210 (char 209), Line: 356
Failed to read data: b' \x00\x00\x00DHIP\xee<5m\x08\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Start","Code":"CallNoAnswered","Data":{"CallID":"3","LocaleTime":"2022-02-25 10:18:56","UTC":1645802336.0},"Index":0}]},"session":183220', error: Expecting ',' delimiter: line 1 column 208 (char 207), Line: 356
```

**Comment by calisro** [comment]
I actually wonder if part of the issue here is that we're not enabling all the events the AD410 requires.  I can see in the list of events that most are available not no one knows what to select for a particular device.  Such as 'BackKeyLight, IntelliFrame, CallNoAnswered are called out above.  I deleted the integration today and selected ALL events.  Yes that leaves quite a bit of useless entities but I'm going to see what errors I receive now.  I assume quite a bit of the noise above will go away but more importantly, I wonder if it will stabilize the integration.

**Comment by calisro** [comment]
I'm seeing far less errors in the logs.  Today it stopped detecting motion and these are the events in my logs:

```
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Start","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4093],[0,8191],[8191,8191],[8191,4093],[8191,0]],"EventID":16131,"EventSeq":5916,"FrameSequence":23212202,"GroupID":5916,"LocaleTime":"2022-02-28 15:42:26","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingB''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4093],[0,8191],[8191,8191],[8191,4093],[8191,0]],"EventID":16131,"EventSeq":5916,"FrameSequence":23212202,"GroupID":5916,"LocaleTime":"2022-02-28 15:42:57","Mark":0,"Name":"IVS-1","Object":{"Action":"Appear","Age":0,"Angle":0,"Bag":0,"BagType":0,"BoundingBox":
```

```
Failed to read data: b' \x00\x00\x00DHIP\xde\xc6\x1a2\x08\x00\x00\x00\xe1\x00\x00\x00\x00\x00\x00\x00\xe1\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"BackKeyLight","Data":{"LocaleTime":"2022-02-28 14:41:46","State":4,"UTC":1646077306.0},"Index":-1}]},"session":840615646}\n \x00\x00\x00DHIP\xde\xc6\x1a2\x08\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"IntelliFrame","Data":{"Action":"Stop","LocaleTime":"2022-02-28 14:41:49","UTC":1646077309.0},"Index":0}]},"session":8406', error: Expecting ',' delimiter: line 1 column 209 (char 208), Line: 356
```

The doorbell button is still functioning just fine but person motion isn't.

**Comment by frustreermeneer** [comment]
> ```
> Failed to read data: b' \x00\x00\x00DHIP\xde\xc6\x1a2\x08\x00\x00\x00\xe1\x00\x00\x00\x00\x00\x00\x00\xe1\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"BackKeyLight","Data":{"LocaleTime":"2022-02-28 14:41:46","State":4,"UTC":1646077306.0},"Index":-1}]},"session":840615646}\n \x00\x00\x00DHIP\xde\xc6\x1a2\x08\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"IntelliFrame","Data":{"Action":"Stop","LocaleTime":"2022-02-28 14:41:49","UTC":1646077309.0},"Index":0}]},"session":8406', error: Expecting ',' delimiter: line 1 column 209 (char 208), Line: 356
> ```
> 
> The doorbell button is still functioning just fine but person motion isn't.

I'm experiencing the same. It seems the second message it receives is not correct json. It seems to be missing the last '}' ?

**Comment by hasan-fardan** [comment]
I am getting this

2022-04-18 17:26:03 DEBUG (Thread-336) [custom_components.dahua] Event data 192.168.1.110: 'b' \x00\x00\x00DHIP\xe2\xfe\xff\x7f\x08\x00\x00\x00\x0f\x01\x00\x00\x00\x00\x00\x00\x0f\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"APConnect","Data":{"Error":"SSIDNotValid","LocaleTime":"2022-04-18 17:26:03","Result":false,"Type":"Timerconnect","UTC":1650291963.0},"Index":0}]},"session":2147483362}\n''
2022-04-18 17:26:03 DEBUG (Thread-336) [custom_components.dahua] VTO Data received: {'Action': 'Stop', 'Code': 'APConnect', 'Data': {'Error': 'SSIDNotValid', 'LocaleTime': '2022-04-18 17:26:03', 'Result': False, 'Type': 'Timerconnect', 'UTC': 1650291963.0}, 'Index': 0, 'serialNumber': '4G03F5CAAZ2E22A', 'deviceType': 'VTO2111D', 'DeviceName': 'Doorbell'}

**Comment by calisro** [comment]
This continues to be an issue and makes it VERY unreliable.  There is no way to tell that the doorbell push and human detection is no longer working without pushing it.  I am finding even re-loading the integtation doesn't fix it.  Rebooting HA does though which is interesting.

**Comment by calisro** [comment]
Posted this to the wrong issue before. Incase you need it here:

Since this is unstable for AD410, I switched for now to the HA native integration and setup events for button, human, motion and this is now working pretty well for those having trouble.  I prefer this integration because it has more features but stability is THE concern.  I can't have people ringing the bell with the integration not detecting it and requiring me to restart HA.

Config:
```
amcrest:
  - host: 10.100.1.143
    username: admin
    password: xxxxxx
    name: Front Door Bell
    resolution: high
    stream_source: rtsp
    scan_interval: 15
    binary_sensors:
      - online
    switches:
      - privacy_mode
  - host: 10.100.1.143
    username: admin
    password: xxxxxxx
    name: Front Door Bell Sub
    resolution: low
    stream_source: rtsp
    scan_interval: 305
```


Template Triggers:
```
template:
  - trigger:
      - platform: event
        event_type: amcrest
        id: start
        event_data:
          camera: "Front Door Bell"
          event: CrossRegionDetection
          payload:
            code: CrossRegionDetection
            action: Start
            data:
              Action: Appear
              object:
                ObjectType: Human  
      - platform: event
        event_type: amcrest
        id: stop
        event_data:
          camera: "Front Door Bell"
          event: CrossRegionDetection
          payload:
            code: CrossRegionDetection
            action: Stop
            data:
              Action: Appear
              object:
                ObjectType: Human  
    binary_sensor:
      - name: Front Door Bell Human
        icon: mdi:motion-sensor
        state: >-
          {{ 'on' if trigger.id == 'start' else 'off' }}
        

  - trigger:
      - platform: event
        event_type: amcrest
        id: start
        event_data:
          camera: "Front Door Bell"
          event: CallNoAnswered
          payload:
            code: CallNoAnswered
            action: Start
      - platform: event
        event_type: amcrest
        id: stop
        event_data:
          camera: "Front Door Bell"
          event: CallNoAnswered
          payload:
            code: CallNoAnswered
            action: Stop
    binary_sensor:
      - name: Front Door Bell Ring
        icon: mdi:doorbell-video
        state: >-
          {{ 'on' if trigger.id == 'start' else 'off' }}

  - trigger:
      - platform: event
        event_type: amcrest
        id: start
        event_data:
          camera: "Front Door Bell"
          event: VideoMotion
          payload:
            code: VideoMotion
            action: Start
            data:
              Action: Appear
              object:
      - platform: event
        event_type: amcrest
        id: stop
        event_data:
          camera: "Front Door Bell"
          event: VideoMotion
          payload:
            code: VideoMotion
            action: Stop
            data:
              Action: Appear
    binary_sensor:
      - name: Front Door Bell Motion
        icon: mdi:motion
        state: >-
          {{ 'on' if trigger.id == 'start' else 'off' }}
```

**Comment by junalmeida** [comment]
I'm also getting this:

```
This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:358
Integration: Dahua (documentation, issues)
First occurred: 6:29:32 AM (86 occurrences)
Last logged: 7:56:40 AM

Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"NewFile","Data":{"File":"\\/mnt\\/sd\\/2022-06-30\\/001\\/jpg\\/07\\/54\\/58[M][0@0][1].jpg","LocaleTime":"2022-06-30 07:54:59","''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"TimeChange","Data":{"BeforeModifyTime":"2022-06-30 07:55:21","LocaleTime":"2022-06-30 07:55:21","ModifiedTime":"2022-06-3''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"NTPAdjustTime","Data":{"Address":"200.160.0.8","Before":"2022-06-30 07:55:20","LocaleTime":"2022-06-30 07:55:21","UTC":16''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","CfgRuleId":1,"Class":"Normal","CountInGroup":0,"DetectRegion":[[0,0],[0,4''
Malformed or truncated message returned from device '{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"NewFile","Data":{"File":"\\/mnt\\/sd\\/2022-06-30\\/001\\/jpg\\/07\\/56\\/39[F][0@0][0].jpg","LocaleTime":"2022-06-30 07:56:39","''
```

**Comment by rroller** [comment]
Can you please try the latest version 0.9.43?

I added a better JSON extractor that will handle extracting multiple JSON elements from a string and handle multi line elements

https://github.com/rroller/dahua/releases/tag/0.9.43

**Comment by zios0007** [comment]
Worth a retest. "Fails to read data and goes offline" was a symptom with several distinct causes, and they have been dealt with separately since 2022.

| | | |
|---|---|---|
| #630 | back off a device that has stopped answering, instead of hammering it at the configured interval | 0.9.91 |
| #645 | decide the event stream retry on whether the device spoke, not on how long the connection lasted | 0.9.94 |
| #663 | a failed poll must not write over an event, so a timeout stops blanking sensors that had just fired | 0.9.98 |
| #705 | one unparseable payload no longer kills the stream for every channel on the device | 0.10.10 |
| #712 | one config table a device refuses no longer costs it the whole RPC2 transport | 0.10.9 |

**#663 is the one that most resembles "goes offline"**: a device that answers slowly had its entities written back to unavailable by the poll, wiping out state the event stream had just delivered. That looks exactly like a camera dropping in and out while events are arriving fine.

For an AD410 in particular, the doorbell path also gained #718 (Pulse handling restored on the CGI path) and #719 (a press reported as `State 2` is now accepted), both of which cause silence rather than offline but are worth knowing.

If it still drops on a current version, the log says considerably more than it did in 2022: #627 reports stream failures rather than swallowing them, and #721 logs every write. The line naming the failure would be the thing to post.
