### ISSUE TITLE
Issue with Dahua TiOC 3 / TiOC Pro and Security Light

### ISSUE THREAD

**Issue by lusantor** [rroller/dahua#494]
Hi everyone,
I’m experiencing a strange behavior with the new Dahua TiOC 3 and TiOC Pro cameras compared to the previous TiOC 2 models.

 If I enable the Security Light from the Dahua DMSS app, the alarm light turns on correctly.
 However, in Home Assistant the Security Light switch does not update and remains off.

Additionally:
 If I try to enable the light directly from the Home Assistant switch, with the TiOC 3/Pro the light does not turn on at all.
 With the TiOC 2, everything works correctly in both directions (DMSS ↔ Home Assistant).

It looks like there might be a compatibility issue or a different API handling in the newer TiOC versions.

 Has anyone else experienced the same behavior?
Is there already a fix or workaround (firmware update, configuration, or integration patch) to keep DMSS and Home Assistant properly in sync?

Thanks to anyone who can share their experience

**Comment by zios0007** [comment]
@lusantor this is the same problem as #546 — same symptom, same camera generation, reported six months apart with no reply on either. Worth reading together rather than separately, and I would suggest closing this one in favour of #546 so the evidence sits in one place.

Both reports say the TiOC 3 / Pro security light fails in Home Assistant while **TiOC 2 works on the same setup**, and both note the DMSS app and Home Assistant disagreeing about the state.

That generational split now has company. #446 reports the same thing on a DH-IPC-HDW3649H-AS-PV — the light physically activates while the Home Assistant toggle springs back to off — on firmware **3.140**. And #647 has three cameras on 3.140 where lighting commands are accepted, stored, and produce nothing visible.

The relevant finding from #647, measured by @roby-esc: their camera switched physically between infrared and white light **with no change in `VideoInMode`, `Lighting`, `Lighting_V2` or `LightingScheme`**. Their conclusion — *these tables describe configuration, not the current physical light state* — fits your report exactly. If the camera's own logic is driving the light, Home Assistant reading a config table will disagree with what you can see, in both directions.

**If you still have the cameras**, the check that would tie this to the cluster:

```bash
curl -s --digest -u admin:PASSWORD \
  "http://CAMERA-IP/cgi-bin/configManager.cgi?action=getConfig&name=LightingScheme"
```

`LightingMode=AIMode` means the camera is in Smart Dual Light and is entitled to override what Home Assistant asks for. `Bad Request!` means your model has no such table, which would separate your cameras from the #647 group and is equally useful to know.

I have no TiOC to test, so this is a connection between reports rather than a diagnosis of yours.

**Comment by lsantoro** [comment]
This issue affecting the **Security Light status on the new TIOC3/TIOC Pro models** was fixed a few months ago by the changes introduced in **PR #550**:

**Fix TIOC3/TIOC Pro status parsing**
https://github.com/rroller/dahua/pull/550

The fix addresses the status parsing for these models, including the Security Light state.

Therefore, **version 0.9.96 already contains the fix and does not have this issue**.

**Comment by zios0007** [comment]
@lsantoro you are right and I was wrong — thanks for the correction.

I filed this issue in with the 3.140 lighting cluster (#446, #546, #647). For the **status** half of it that was a mistake, and I have checked rather than taking it on trust:

- **#550 merged 2026-03-07**, adding `get_status_value`, which reads both `status.status.WhiteLight` and `status.WhiteLight` so TiOC 3 / Pro report their light state like TiOC 2 does.
- **This issue was filed 2025-08-26**, so it predates that fix by six months. The symptom described here is exactly what #550 addresses.

So the "Home Assistant and DMSS disagree about the light state" part of this report should be gone on anything from 0.9.90 onwards, and it is certainly in 0.9.98.

What I said about #647 still stands on its own, but it is a different problem and I should not have attached this issue to it: there, lighting commands are accepted and stored while the physical light does its own thing on firmware 3.140. That is about *control*, not about parsing a status field, and nothing in it suggests this report was ever the same fault.

@lusantor if you still have the cameras, could you confirm the security light state now tracks correctly on a current version? If it does, this can be closed — and #546 with it, since @lsantoro has already confirmed the fix there.

**Comment by zios0007** [comment]
Correcting my own figure above: I said "from 0.9.90 onwards", which is true but understates it by thirteen releases.

Checked properly — #550's merge commit is in **0.9.77** and everything after it:

```
$ git tag --contains a30c975
0.9.77
0.9.78
0.9.79
...
```

0.9.77 went out on 2026-03-08. So anyone on that or later already has the fix, not just 0.9.90+.

**Comment by lusantor** [comment]
I can confirm that I still have the cameras, and the security light state is now correctly tracked in the current version.

The issue described here is therefore resolved by the status parsing fix in #550.

This issue can be closed, along with #546.
